index:
    path:     /
    defaults: { _controller: ShinagePlayerBundle:Index:index }

current:
    path:     /current
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:current }

test:
    path:     /test
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:test }
