shinage.player.index:
    path:     /
    defaults: { _controller: ShinagePlayerBundle:Index:index }

shinage.player.current:
    path:     /current
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:current }

shinage.player.splash:
    path:     /p/splash
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:splash }

shinage.player.test:
    path:     /p/test
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:test }

shinage.player.presentation.local:
    path:     /p/local/{name}
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:local }

shinage.player.file.local:
    path:     /f/local/{presentation}/{file}
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:localFile }

shinage.player.presentation.remote:
    path:     /p/remote/{id}
    defaults: { _controller: ShinagePlayerBundle:PresentationViewer:remote }
