services:
  shinage.player.guid_creator:
    class: mztx\ShinagePlayerBundle\Service\GuidCreator

  shinage.player.url_builder:
    class: mztx\ShinagePlayerBundle\Service\UrlBuilder
    arguments:
      $protocol: "%shinage.player.remote.protocol%"
      $host: "%shinage.player.remote.host%"
      $basePath: "%shinage.player.remote.base_path%"
      $controllers: "%shinage.player.remote.controllers%"

  shinage.player.remote.heartbeat:
    class: mztx\ShinagePlayerBundle\Service\Heartbeat
    arguments:
      $urlBuilder: "@shinage.player.url_builder"

  shinage.player.local_scheduler:
    class: mztx\ShinagePlayerBundle\Service\LocalScheduler
    arguments:
      $localProvider: "@shinage.player.local_presentation_provider"

  shinage.player.local_presentation_loader:
    class: mztx\ShinagePlayerBundle\Service\LocalPresentationLoader
    arguments:
      $kernel: "@kernel"
      $basePath: "%shinage.player.local.base_path%"

  shinage.player.local_presentation_provider:
    class: mztx\ShinagePlayerBundle\Service\LocalPresentationProvider
    arguments:
      $kernel: "@kernel"
      $basePath: "%shinage.player.local.base_path%"
      $presentationLoader: "@shinage.player.local_presentation_loader"
