framework:
  secret: "klsdfgisezo75ctzno4789zto8e7sfmcsx"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  templating:
    engines: ['twig']
  assets: ~

twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

shinage_player:
  uuid: "00000000-0000-0000-0000-000000000000"
  local:
    enabled: true
    path: "/mnt/usb"
  remote:
    enabled: true
    host: "shinage.mztx.de"
    protocol: "https"
    base_path: "/shinage"
    controller:
      heartbeat: "/screen-remote/heartbeat/%s"
      presentation: "/screen-remote/presentation/%d"
      asset: "/screen-remote/client-file/%s"
      screenshot: "/screen-remote/upload-screenshot"

