# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "debian/jessie64"
  config.ssh.insert_key = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application server
  config.vm.define "shinage-player" do |app|
    app.vm.hostname = "shinage-player.dev"
    app.vm.network :private_network, ip: "10.251.0.102"
  end
end
